---
clusterOverrides:
  primary:
    name: suvro-primary
    version: "4.21.10"
  secondary:
    name: suvro-secondary
    version: "4.21.10"

drpc:
  preferredCluster: suvro-primary
  protectedNamespaces:
    - gitops-vms
    - boutique

byoc: true
