---
waitForMetalNode: false
disableExternalSecrets: true
vmDefaults:
  count: 0
  publishService: false
vms: {}
boutique:
  deploy: false
redis:
  external:
    enabled: false

regionalDR:
  - name: resilient
    globalnetEnabled: false
    clusters:
      primary:
        name: ocp-primary
        clusterGroup: resilient
      secondary:
        name: ocp-secondary
        clusterGroup: resilient
    drpolicies:
      - interval: 2m

drpc:
  drPolicyRef:
    name: 2m-novm
